version: '2'

services:
  users_web:
    build: ./users
    command: bash -c "python3 ./users/manage.py runserver 0.0.0.0:8001"
    volumes:
      - .:/code
    ports:
      - 8001:8001
    restart: always
      
  nginx:
    build: ./web
    ports:
      - 81:80
    links:
      - users_web
    depends_on:
      - users_web
