version: '2'

services:
  users_web:
    build: ./users
    command: bash -c "cd users && gunicorn api.wsgi --bind 0.0.0.0:80 --reload"
    volumes:
      - .:/code
    ports:
      - 80:80
    restart: always
